"use client";

import { useEffect, useMemo, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import {
  useListApplicationsApplicationsGet,
  useCreateApplicationApplicationsPost,
  useUpdateApplicationApplicationsApplicationIdPatch,
  useDeleteApplicationApplicationsApplicationIdDelete,
  getListApplicationsApplicationsGetQueryKey,
  useListApplicantsApplicantsGet,
} from "@/lib/api-client/generated";
import type { ApplicationResponse } from "@/lib/api-client/generated/models";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { readClientSession, canWrite, canDelete } from "@/lib/session";

// Mirrors app/models/applications.py's ApplicationBase exactly (confirmed
// against the real Supabase "applications" table + pg_constraint audit).
// application_no is excluded: server-generated by a BEFORE INSERT trigger
// (generate_application_no()) and not exposed on the backend's own
// ApplicationUpdate model either. programme and allotted_seat_type are
// rendered as selects because they're genuinely DB CHECK-constrained
// (applications_programme_check / applications_allotted_seat_type_check) -
// same reasoning that kept Leads.status as free text, since that field has
// no such constraint.
type ApplicationFormValues = {
  applicant_id: string;
  academic_year: string;
  programme: string;
  department: string;
  branch: string;
  preferred_hostel: boolean;
  preferred_transport: boolean;
  transport_route: string;
  application_stage: string;
  merit_rank: string;
  allotted_seat_type: string;
  remarks: string;
  submitted_at: string;
  reviewed_by: string;
  reviewed_at: string;
  category: string;
};

const emptyForm: ApplicationFormValues = {
  applicant_id: "",
  academic_year: "",
  programme: "",
  department: "",
  branch: "",
  preferred_hostel: false,
  preferred_transport: false,
  transport_route: "",
  application_stage: "",
  merit_rank: "",
  allotted_seat_type: "",
  remarks: "",
  submitted_at: "",
  reviewed_by: "",
  reviewed_at: "",
  category: "",
};

const str = (v: string | null | undefined) => v ?? "";
const num = (v: number | null | undefined) => (v === null || v === undefined ? "" : String(v));
// API returns full ISO datetimes; <input type="datetime-local"> needs the
// "YYYY-MM-DDTHH:mm" form with no timezone suffix.
const toLocalInput = (v: string | null | undefined) => (v ? v.slice(0, 16) : "");

const PROGRAMMES = ["B.E.", "B.Tech", "M.E.", "M.Tech", "MBA", "MCA"];
const SEAT_TYPES = ["Management", "Government", "NRI", "Lateral Entry", "Spot"];

function toPayload(form: ApplicationFormValues) {
  return {
    applicant_id: form.applicant_id,
    academic_year: form.academic_year || null,
    programme: form.programme,
    department: form.department,
    branch: form.branch || null,
    preferred_hostel: form.preferred_hostel,
    preferred_transport: form.preferred_transport,
    transport_route: form.transport_route || null,
    application_stage: form.application_stage || null,
    merit_rank: form.merit_rank ? Number(form.merit_rank) : null,
    allotted_seat_type: form.allotted_seat_type || null,
    remarks: form.remarks || null,
    submitted_at: form.submitted_at ? new Date(form.submitted_at).toISOString() : null,
    reviewed_by: form.reviewed_by || null,
    reviewed_at: form.reviewed_at ? new Date(form.reviewed_at).toISOString() : null,
    category: form.category || null,
  };
}

export default function ApplicationsPage() {
  const queryClient = useQueryClient();
  const [role, setRole] = useState<string | undefined>(undefined);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editingApplication, setEditingApplication] = useState<ApplicationResponse | null>(null);
  const [form, setForm] = useState<ApplicationFormValues>(emptyForm);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setRole(readClientSession()?.role);
  }, []);

  const listQuery = useListApplicationsApplicationsGet({ limit: 50, offset: 0 });
  // Applicant picker + display-name lookup. 200 is a pragmatic ceiling for
  // a <select>-style picker; once applicant volume outgrows that, this
  // needs a searchable combobox hitting the list endpoint with a query
  // param instead - not needed yet at Phase A's data volume.
  const applicantsQuery = useListApplicantsApplicantsGet({ limit: 200, offset: 0 });
  const createMutation = useCreateApplicationApplicationsPost();
  const updateMutation = useUpdateApplicationApplicationsApplicationIdPatch();
  const deleteMutation = useDeleteApplicationApplicationsApplicationIdDelete();

  const applications: ApplicationResponse[] =
    listQuery.data?.status === 200 ? listQuery.data.data.items : [];
  const applicants = useMemo(
    () => (applicantsQuery.data?.status === 200 ? applicantsQuery.data.data.items : []),
    [applicantsQuery.data]
  );

  const applicantLabel = useMemo(() => {
    const map = new Map<string, string>();
    for (const a of applicants) {
      map.set(a.id, `${a.first_name} ${a.last_name}${a.reg_number ? ` (${a.reg_number})` : ""}`);
    }
    return (id: string) => map.get(id) ?? id;
  }, [applicants]);

  const invalidateList = () =>
    queryClient.invalidateQueries({
      queryKey: getListApplicationsApplicationsGetQueryKey({ limit: 50, offset: 0 }),
    });

  const openCreate = () => {
    setEditingApplication(null);
    setForm(emptyForm);
    setDialogOpen(true);
  };

  const openEdit = (a: ApplicationResponse) => {
    setEditingApplication(a);
    setForm({
      applicant_id: a.applicant_id,
      academic_year: str(a.academic_year),
      programme: a.programme,
      department: a.department,
      branch: str(a.branch),
      preferred_hostel: a.preferred_hostel ?? false,
      preferred_transport: a.preferred_transport ?? false,
      transport_route: str(a.transport_route),
      application_stage: str(a.application_stage),
      merit_rank: num(a.merit_rank),
      allotted_seat_type: str(a.allotted_seat_type),
      remarks: str(a.remarks),
      submitted_at: toLocalInput(a.submitted_at as unknown as string),
      reviewed_by: str(a.reviewed_by as unknown as string),
      reviewed_at: toLocalInput(a.reviewed_at as unknown as string),
      category: str(a.category),
    });
    setDialogOpen(true);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.applicant_id) {
      toast.error("Pick an applicant first.");
      return;
    }
    const payload = toPayload(form);

    if (editingApplication) {
      updateMutation.mutate(
        { applicationId: editingApplication.id, data: payload },
        {
          onSuccess: (res) => {
            if (res.status === 200) {
              toast.success("Application updated");
              setDialogOpen(false);
              invalidateList();
            }
          },
        }
      );
    } else {
      createMutation.mutate(
        { data: payload },
        {
          onSuccess: (res) => {
            if (res.status === 201) {
              toast.success("Application created");
              setDialogOpen(false);
              invalidateList();
            }
          },
        }
      );
    }
  };

  const handleDelete = (a: ApplicationResponse) => {
    if (!confirm(`Delete application "${a.application_no ?? a.id}"? This cannot be undone.`)) return;
    deleteMutation.mutate(
      { applicationId: a.id },
      {
        onSuccess: (res) => {
          if (res.status === 204) {
            toast.success("Application deleted");
            invalidateList();
          }
        },
      }
    );
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold">Applications</h1>
          <p className="text-sm text-muted-foreground">
            {listQuery.data?.status === 200 ? listQuery.data.data.total : "..."} total
          </p>
        </div>
        {canWrite(role) && (
          <Button onClick={openCreate} disabled={applicants.length === 0}>
            New application
          </Button>
        )}
      </div>

      {canWrite(role) && applicants.length === 0 && !applicantsQuery.isLoading && (
        <p className="text-sm text-muted-foreground">
          No applicants yet - add one on the Applicants page before creating an application.
        </p>
      )}

      {listQuery.isLoading && <p className="text-sm text-muted-foreground">Loading...</p>}
      {listQuery.isError && <p className="text-sm text-destructive">Failed to load applications.</p>}

      {listQuery.data?.status === 200 && (
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Application no.</TableHead>
              <TableHead>Applicant</TableHead>
              <TableHead>Programme</TableHead>
              <TableHead>Department</TableHead>
              <TableHead>Stage</TableHead>
              <TableHead>Seat type</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {applications.map((a) => (
              <TableRow key={a.id}>
                <TableCell className="font-medium">{a.application_no ?? "-"}</TableCell>
                <TableCell>{applicantLabel(a.applicant_id)}</TableCell>
                <TableCell>{a.programme}</TableCell>
                <TableCell>{a.department}</TableCell>
                <TableCell>
                  <Badge variant="secondary">{a.application_stage ?? "Draft"}</Badge>
                </TableCell>
                <TableCell>{a.allotted_seat_type ?? "-"}</TableCell>
                <TableCell className="text-right space-x-2">
                  {canWrite(role) && (
                    <Button variant="outline" size="sm" onClick={() => openEdit(a)}>
                      Edit
                    </Button>
                  )}
                  {canDelete(role) && (
                    <Button variant="destructive" size="sm" onClick={() => handleDelete(a)}>
                      Delete
                    </Button>
                  )}
                </TableCell>
              </TableRow>
            ))}
            {applications.length === 0 && (
              <TableRow>
                <TableCell colSpan={7} className="text-center text-muted-foreground">
                  No applications yet.
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      )}

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="max-w-xl max-h-[85vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>{editingApplication ? "Edit application" : "New application"}</DialogTitle>
          </DialogHeader>
          <form onSubmit={handleSubmit} className="space-y-3">
            <div className="space-y-1.5">
              <Label htmlFor="applicant_id">Applicant *</Label>
              <Select
                value={form.applicant_id}
                onValueChange={(v) => setForm({ ...form, applicant_id: v })}
                disabled={!!editingApplication}
              >
                <SelectTrigger id="applicant_id">
                  <SelectValue placeholder="Select an applicant" />
                </SelectTrigger>
                <SelectContent>
                  {applicants.map((a) => (
                    <SelectItem key={a.id} value={a.id}>
                      {a.first_name} {a.last_name}
                      {a.reg_number ? ` (${a.reg_number})` : ` - ${a.phone}`}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {editingApplication && (
                <p className="text-xs text-muted-foreground">
                  Applicant can&apos;t be changed after creation.
                </p>
              )}
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label htmlFor="programme">Programme *</Label>
                <Select
                  value={form.programme}
                  onValueChange={(v) => setForm({ ...form, programme: v })}
                >
                  <SelectTrigger id="programme">
                    <SelectValue placeholder="Select" />
                  </SelectTrigger>
                  <SelectContent>
                    {PROGRAMMES.map((p) => (
                      <SelectItem key={p} value={p}>
                        {p}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="department">Department *</Label>
                <Input
                  id="department"
                  required
                  value={form.department}
                  onChange={(e) => setForm({ ...form, department: e.target.value })}
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label htmlFor="branch">Branch</Label>
                <Input
                  id="branch"
                  value={form.branch}
                  onChange={(e) => setForm({ ...form, branch: e.target.value })}
                />
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="academic_year">Academic year</Label>
                <Input
                  id="academic_year"
                  placeholder="e.g. 2026-27"
                  value={form.academic_year}
                  onChange={(e) => setForm({ ...form, academic_year: e.target.value })}
                />
              </div>
            </div>

            <div className="flex items-center gap-6">
              <div className="flex items-center gap-2">
                <Checkbox
                  id="preferred_hostel"
                  checked={form.preferred_hostel}
                  onCheckedChange={(c) => setForm({ ...form, preferred_hostel: c === true })}
                />
                <Label htmlFor="preferred_hostel">Hostel preferred</Label>
              </div>
              <div className="flex items-center gap-2">
                <Checkbox
                  id="preferred_transport"
                  checked={form.preferred_transport}
                  onCheckedChange={(c) => setForm({ ...form, preferred_transport: c === true })}
                />
                <Label htmlFor="preferred_transport">Transport preferred</Label>
              </div>
            </div>

            {form.preferred_transport && (
              <div className="space-y-1.5">
                <Label htmlFor="transport_route">Transport route</Label>
                <Input
                  id="transport_route"
                  value={form.transport_route}
                  onChange={(e) => setForm({ ...form, transport_route: e.target.value })}
                />
              </div>
            )}

            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label htmlFor="application_stage">Stage</Label>
                <Input
                  id="application_stage"
                  placeholder="Draft"
                  value={form.application_stage}
                  onChange={(e) => setForm({ ...form, application_stage: e.target.value })}
                />
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="merit_rank">Merit rank</Label>
                <Input
                  id="merit_rank"
                  type="number"
                  value={form.merit_rank}
                  onChange={(e) => setForm({ ...form, merit_rank: e.target.value })}
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label htmlFor="allotted_seat_type">Allotted seat type</Label>
                <Select
                  value={form.allotted_seat_type}
                  onValueChange={(v) => setForm({ ...form, allotted_seat_type: v })}
                >
                  <SelectTrigger id="allotted_seat_type">
                    <SelectValue placeholder="Not allotted" />
                  </SelectTrigger>
                  <SelectContent>
                    {SEAT_TYPES.map((s) => (
                      <SelectItem key={s} value={s}>
                        {s}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="category">Category</Label>
                <Input
                  id="category"
                  value={form.category}
                  onChange={(e) => setForm({ ...form, category: e.target.value })}
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label htmlFor="submitted_at">Submitted at</Label>
                <Input
                  id="submitted_at"
                  type="datetime-local"
                  value={form.submitted_at}
                  onChange={(e) => setForm({ ...form, submitted_at: e.target.value })}
                />
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="reviewed_at">Reviewed at</Label>
                <Input
                  id="reviewed_at"
                  type="datetime-local"
                  value={form.reviewed_at}
                  onChange={(e) => setForm({ ...form, reviewed_at: e.target.value })}
                />
              </div>
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="reviewed_by">Reviewed by (user ID)</Label>
              <Input
                id="reviewed_by"
                value={form.reviewed_by}
                onChange={(e) => setForm({ ...form, reviewed_by: e.target.value })}
              />
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="remarks">Remarks</Label>
              <Textarea
                id="remarks"
                rows={3}
                value={form.remarks}
                onChange={(e) => setForm({ ...form, remarks: e.target.value })}
              />
            </div>

            <DialogFooter>
              <Button
                type="submit"
                disabled={createMutation.isPending || updateMutation.isPending}
              >
                {editingApplication ? "Save changes" : "Create application"}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  );
}
