"use client";

import { useEffect, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import {
  useListApplicantsApplicantsGet,
  useCreateApplicantApplicantsPost,
  useUpdateApplicantApplicantsApplicantIdPatch,
  useDeleteApplicantApplicantsApplicantIdDelete,
  getListApplicantsApplicantsGetQueryKey,
} from "@/lib/api-client/generated";
import type { ApplicantResponse } from "@/lib/api-client/generated/models";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { readClientSession, canWrite, canDelete } from "@/lib/session";

// Every field here mirrors app/models/applicants.py's ApplicantBase exactly
// (confirmed against the real Supabase "applicants" table). Three fields
// from that model are intentionally NOT in this form:
//   - reg_number: server-generated by a BEFORE INSERT trigger, unique,
//     never client-settable.
//   - created_by: set once at creation from the authenticated caller,
//     not exposed on PATCH by the backend's own ApplicantUpdate model.
//   - doc_status: a free-form JSON document-checklist blob, not a form
//     field - a dedicated document checklist UI is future work.
// Several fields are legacy duplicates carried over from the old Streamlit
// schema (full_name/mobile/dob/address/hsc_percentage alongside
// first_name+last_name/phone/date_of_birth/address_line1/twelfth_percentage).
// They're kept here, labeled "(legacy)", because the backend model keeps
// them verbatim per the audit-first rule - not cleaned up on the frontend
// either.
type ApplicantFormValues = {
  first_name: string;
  last_name: string;
  full_name: string;
  gender: string;
  date_of_birth: string;
  dob: string;
  phone: string;
  alternate_phone: string;
  mobile: string;
  email: string;
  blood_group: string;
  address_line1: string;
  address_line2: string;
  address: string;
  city: string;
  state: string;
  pincode: string;
  school_name: string;
  twelfth_school: string;
  twelfth_board: string;
  twelfth_year: string;
  twelfth_percentage: string;
  twelfth_group: string;
  hsc_percentage: string;
  pcm_marks: string;
  cutoff_marks: string;
  entrance_exam: string;
  entrance_rank: string;
  entrance_score: string;
  programme_interested: string;
  department_interested: string;
  parent_name: string;
  parent_phone: string;
  parent_occupation: string;
  annual_income: string;
  father_name: string;
  mother_name: string;
  father_mobile: string;
  category: string;
  community_cert_no: string;
  aadhaar_number: string;
  lead_source: string;
  referred_by: string;
  reference_name: string;
  assigned_counselor: string;
  status: string;
  priority: string;
  notes: string;
};

const emptyForm: ApplicantFormValues = {
  first_name: "",
  last_name: "",
  full_name: "",
  gender: "",
  date_of_birth: "",
  dob: "",
  phone: "",
  alternate_phone: "",
  mobile: "",
  email: "",
  blood_group: "",
  address_line1: "",
  address_line2: "",
  address: "",
  city: "",
  state: "",
  pincode: "",
  school_name: "",
  twelfth_school: "",
  twelfth_board: "",
  twelfth_year: "",
  twelfth_percentage: "",
  twelfth_group: "",
  hsc_percentage: "",
  pcm_marks: "",
  cutoff_marks: "",
  entrance_exam: "",
  entrance_rank: "",
  entrance_score: "",
  programme_interested: "",
  department_interested: "",
  parent_name: "",
  parent_phone: "",
  parent_occupation: "",
  annual_income: "",
  father_name: "",
  mother_name: "",
  father_mobile: "",
  category: "",
  community_cert_no: "",
  aadhaar_number: "",
  lead_source: "",
  referred_by: "",
  reference_name: "",
  assigned_counselor: "",
  status: "",
  priority: "Normal",
  notes: "",
};

const str = (v: string | null | undefined) => v ?? "";
const num = (v: number | null | undefined) => (v === null || v === undefined ? "" : String(v));

function toPayload(form: ApplicantFormValues) {
  return {
    first_name: form.first_name,
    last_name: form.last_name,
    full_name: form.full_name || null,
    gender: form.gender || null,
    date_of_birth: form.date_of_birth || null,
    dob: form.dob || null,
    phone: form.phone,
    alternate_phone: form.alternate_phone || null,
    mobile: form.mobile || null,
    email: form.email || null,
    blood_group: form.blood_group || null,
    address_line1: form.address_line1 || null,
    address_line2: form.address_line2 || null,
    address: form.address || null,
    city: form.city || null,
    state: form.state || null,
    pincode: form.pincode || null,
    school_name: form.school_name || null,
    twelfth_school: form.twelfth_school || null,
    twelfth_board: form.twelfth_board || null,
    twelfth_year: form.twelfth_year ? Number(form.twelfth_year) : null,
    twelfth_percentage: form.twelfth_percentage ? Number(form.twelfth_percentage) : null,
    twelfth_group: form.twelfth_group || null,
    hsc_percentage: form.hsc_percentage ? Number(form.hsc_percentage) : null,
    pcm_marks: form.pcm_marks ? Number(form.pcm_marks) : null,
    cutoff_marks: form.cutoff_marks ? Number(form.cutoff_marks) : null,
    entrance_exam: form.entrance_exam || null,
    entrance_rank: form.entrance_rank ? Number(form.entrance_rank) : null,
    entrance_score: form.entrance_score ? Number(form.entrance_score) : null,
    programme_interested: form.programme_interested || null,
    department_interested: form.department_interested || null,
    parent_name: form.parent_name || null,
    parent_phone: form.parent_phone || null,
    parent_occupation: form.parent_occupation || null,
    annual_income: form.annual_income ? Number(form.annual_income) : null,
    father_name: form.father_name || null,
    mother_name: form.mother_name || null,
    father_mobile: form.father_mobile || null,
    category: form.category || null,
    community_cert_no: form.community_cert_no || null,
    aadhaar_number: form.aadhaar_number || null,
    lead_source: form.lead_source || null,
    referred_by: form.referred_by || null,
    reference_name: form.reference_name || null,
    assigned_counselor: form.assigned_counselor || null,
    status: form.status || null,
    priority: form.priority || null,
    notes: form.notes || null,
  };
}

export default function ApplicantsPage() {
  const queryClient = useQueryClient();
  const [role, setRole] = useState<string | undefined>(undefined);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editingApplicant, setEditingApplicant] = useState<ApplicantResponse | null>(null);
  const [form, setForm] = useState<ApplicantFormValues>(emptyForm);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setRole(readClientSession()?.role);
  }, []);

  const listQuery = useListApplicantsApplicantsGet({ limit: 50, offset: 0 });
  const createMutation = useCreateApplicantApplicantsPost();
  const updateMutation = useUpdateApplicantApplicantsApplicantIdPatch();
  const deleteMutation = useDeleteApplicantApplicantsApplicantIdDelete();

  const applicants: ApplicantResponse[] =
    listQuery.data?.status === 200 ? listQuery.data.data.items : [];

  const invalidateList = () =>
    queryClient.invalidateQueries({
      queryKey: getListApplicantsApplicantsGetQueryKey({ limit: 50, offset: 0 }),
    });

  const openCreate = () => {
    setEditingApplicant(null);
    setForm(emptyForm);
    setDialogOpen(true);
  };

  const openEdit = (a: ApplicantResponse) => {
    setEditingApplicant(a);
    setForm({
      first_name: str(a.first_name),
      last_name: str(a.last_name),
      full_name: str(a.full_name),
      gender: str(a.gender),
      date_of_birth: str(a.date_of_birth as unknown as string),
      dob: str(a.dob as unknown as string),
      phone: str(a.phone),
      alternate_phone: str(a.alternate_phone),
      mobile: str(a.mobile),
      email: str(a.email),
      blood_group: str(a.blood_group),
      address_line1: str(a.address_line1),
      address_line2: str(a.address_line2),
      address: str(a.address),
      city: str(a.city),
      state: str(a.state),
      pincode: str(a.pincode),
      school_name: str(a.school_name),
      twelfth_school: str(a.twelfth_school),
      twelfth_board: str(a.twelfth_board),
      twelfth_year: num(a.twelfth_year),
      twelfth_percentage: num(a.twelfth_percentage),
      twelfth_group: str(a.twelfth_group),
      hsc_percentage: num(a.hsc_percentage),
      pcm_marks: num(a.pcm_marks),
      cutoff_marks: num(a.cutoff_marks),
      entrance_exam: str(a.entrance_exam),
      entrance_rank: num(a.entrance_rank),
      entrance_score: num(a.entrance_score),
      programme_interested: str(a.programme_interested),
      department_interested: str(a.department_interested),
      parent_name: str(a.parent_name),
      parent_phone: str(a.parent_phone),
      parent_occupation: str(a.parent_occupation),
      annual_income: num(a.annual_income),
      father_name: str(a.father_name),
      mother_name: str(a.mother_name),
      father_mobile: str(a.father_mobile),
      category: str(a.category),
      community_cert_no: str(a.community_cert_no),
      aadhaar_number: str(a.aadhaar_number),
      lead_source: str(a.lead_source),
      referred_by: str(a.referred_by),
      reference_name: str(a.reference_name),
      assigned_counselor: str(a.assigned_counselor as unknown as string),
      status: str(a.status),
      priority: str(a.priority) || "Normal",
      notes: str(a.notes),
    });
    setDialogOpen(true);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const payload = toPayload(form);

    if (editingApplicant) {
      updateMutation.mutate(
        { applicantId: editingApplicant.id, data: payload },
        {
          onSuccess: (res) => {
            if (res.status === 200) {
              toast.success("Applicant updated");
              setDialogOpen(false);
              invalidateList();
            }
          },
        }
      );
    } else {
      createMutation.mutate(
        { data: payload },
        {
          onSuccess: (res) => {
            if (res.status === 201) {
              toast.success("Applicant created");
              setDialogOpen(false);
              invalidateList();
            }
          },
        }
      );
    }
  };

  const handleDelete = (a: ApplicantResponse) => {
    if (!confirm(`Delete applicant "${a.first_name} ${a.last_name}"? This cannot be undone.`)) return;
    deleteMutation.mutate(
      { applicantId: a.id },
      {
        onSuccess: (res) => {
          if (res.status === 204) {
            toast.success("Applicant deleted");
            invalidateList();
          }
        },
      }
    );
  };

  const field = (
    key: keyof ApplicantFormValues,
    label: string,
    type: "text" | "email" | "number" | "date" = "text"
  ) => (
    <div className="space-y-1.5">
      <Label htmlFor={key}>{label}</Label>
      <Input
        id={key}
        type={type}
        value={form[key]}
        onChange={(e) => setForm({ ...form, [key]: e.target.value })}
      />
    </div>
  );

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold">Applicants</h1>
          <p className="text-sm text-muted-foreground">
            {listQuery.data?.status === 200 ? listQuery.data.data.total : "..."} total
          </p>
        </div>
        {canWrite(role) && <Button onClick={openCreate}>New applicant</Button>}
      </div>

      {listQuery.isLoading && <p className="text-sm text-muted-foreground">Loading...</p>}
      {listQuery.isError && <p className="text-sm text-destructive">Failed to load applicants.</p>}

      {listQuery.data?.status === 200 && (
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Name</TableHead>
              <TableHead>Phone</TableHead>
              <TableHead>Reg. no.</TableHead>
              <TableHead>Priority</TableHead>
              <TableHead>Status</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {applicants.map((a) => (
              <TableRow key={a.id}>
                <TableCell className="font-medium">
                  {a.first_name} {a.last_name}
                </TableCell>
                <TableCell>{a.phone}</TableCell>
                <TableCell>{a.reg_number ?? "-"}</TableCell>
                <TableCell>
                  <Badge variant="secondary">{a.priority ?? "Normal"}</Badge>
                </TableCell>
                <TableCell>{a.status ?? "-"}</TableCell>
                <TableCell className="text-right space-x-2">
                  {canWrite(role) && (
                    <Button variant="outline" size="sm" onClick={() => openEdit(a)}>
                      Edit
                    </Button>
                  )}
                  {canDelete(role) && (
                    <Button variant="destructive" size="sm" onClick={() => handleDelete(a)}>
                      Delete
                    </Button>
                  )}
                </TableCell>
              </TableRow>
            ))}
            {applicants.length === 0 && (
              <TableRow>
                <TableCell colSpan={6} className="text-center text-muted-foreground">
                  No applicants yet.
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      )}

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>{editingApplicant ? "Edit applicant" : "New applicant"}</DialogTitle>
          </DialogHeader>
          <form onSubmit={handleSubmit} className="space-y-4">
            <Tabs defaultValue="personal">
              <TabsList className="grid w-full grid-cols-5">
                <TabsTrigger value="personal">Personal</TabsTrigger>
                <TabsTrigger value="address">Address</TabsTrigger>
                <TabsTrigger value="academic">Academic</TabsTrigger>
                <TabsTrigger value="family">Family</TabsTrigger>
                <TabsTrigger value="admin">Admin</TabsTrigger>
              </TabsList>

              <TabsContent value="personal" className="space-y-3 pt-3">
                <div className="grid grid-cols-2 gap-3">
                  {field("first_name", "First name *")}
                  {field("last_name", "Last name *")}
                </div>
                {field("full_name", "Full name (legacy)")}
                <div className="grid grid-cols-2 gap-3">
                  {field("gender", "Gender")}
                  {field("blood_group", "Blood group")}
                </div>
                <div className="grid grid-cols-2 gap-3">
                  {field("date_of_birth", "Date of birth", "date")}
                  {field("dob", "DOB (legacy)", "date")}
                </div>
                <div className="grid grid-cols-2 gap-3">
                  {field("phone", "Phone *")}
                  {field("alternate_phone", "Alternate phone")}
                </div>
                <div className="grid grid-cols-2 gap-3">
                  {field("mobile", "Mobile (legacy)")}
                  {field("email", "Email", "email")}
                </div>
              </TabsContent>

              <TabsContent value="address" className="space-y-3 pt-3">
                {field("address_line1", "Address line 1")}
                {field("address_line2", "Address line 2")}
                {field("address", "Address (legacy, single line)")}
                <div className="grid grid-cols-3 gap-3">
                  {field("city", "City")}
                  {field("state", "State")}
                  {field("pincode", "Pincode")}
                </div>
              </TabsContent>

              <TabsContent value="academic" className="space-y-3 pt-3">
                {field("school_name", "School name")}
                <div className="grid grid-cols-2 gap-3">
                  {field("twelfth_school", "12th school")}
                  {field("twelfth_board", "12th board")}
                </div>
                <div className="grid grid-cols-3 gap-3">
                  {field("twelfth_year", "12th year", "number")}
                  {field("twelfth_percentage", "12th %", "number")}
                  {field("twelfth_group", "12th group")}
                </div>
                {field("hsc_percentage", "HSC % (legacy)", "number")}
                <div className="grid grid-cols-2 gap-3">
                  {field("pcm_marks", "PCM marks", "number")}
                  {field("cutoff_marks", "Cutoff marks", "number")}
                </div>
                <div className="grid grid-cols-3 gap-3">
                  {field("entrance_exam", "Entrance exam")}
                  {field("entrance_rank", "Entrance rank", "number")}
                  {field("entrance_score", "Entrance score", "number")}
                </div>
                <div className="grid grid-cols-2 gap-3">
                  {field("programme_interested", "Programme interested")}
                  {field("department_interested", "Department interested")}
                </div>
              </TabsContent>

              <TabsContent value="family" className="space-y-3 pt-3">
                <div className="grid grid-cols-2 gap-3">
                  {field("parent_name", "Parent name")}
                  {field("parent_phone", "Parent phone")}
                </div>
                <div className="grid grid-cols-2 gap-3">
                  {field("parent_occupation", "Parent occupation")}
                  {field("annual_income", "Annual income", "number")}
                </div>
                <div className="grid grid-cols-3 gap-3">
                  {field("father_name", "Father name")}
                  {field("mother_name", "Mother name")}
                  {field("father_mobile", "Father mobile")}
                </div>
              </TabsContent>

              <TabsContent value="admin" className="space-y-3 pt-3">
                <div className="grid grid-cols-2 gap-3">
                  {field("category", "Category")}
                  {field("community_cert_no", "Community cert. no.")}
                </div>
                {field("aadhaar_number", "Aadhaar number")}
                <div className="grid grid-cols-2 gap-3">
                  {field("lead_source", "Lead source")}
                  {field("referred_by", "Referred by")}
                </div>
                <div className="grid grid-cols-2 gap-3">
                  {field("reference_name", "Reference name")}
                  {field("assigned_counselor", "Assigned counselor (user ID)")}
                </div>
                <div className="grid grid-cols-2 gap-3">
                  {field("status", "Status")}
                  <div className="space-y-1.5">
                    <Label htmlFor="priority">Priority</Label>
                    <Select
                      value={form.priority}
                      onValueChange={(v) => setForm({ ...form, priority: v })}
                    >
                      <SelectTrigger id="priority">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="High">High</SelectItem>
                        <SelectItem value="Normal">Normal</SelectItem>
                        <SelectItem value="Low">Low</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                <div className="space-y-1.5">
                  <Label htmlFor="notes">Notes</Label>
                  <Textarea
                    id="notes"
                    rows={3}
                    value={form.notes}
                    onChange={(e) => setForm({ ...form, notes: e.target.value })}
                  />
                </div>
              </TabsContent>
            </Tabs>

            <DialogFooter>
              <Button
                type="submit"
                disabled={createMutation.isPending || updateMutation.isPending}
              >
                {editingApplicant ? "Save changes" : "Create applicant"}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  );
}
